### ISSUE TITLE
Difficulty to run the code 

### ISSUE THREAD

**Issue by Awais2426** [carnegie/QTG_Finder#3]
Hi,
Thank you very much for writing the QTG code to find orthologues in model species. I am new to Python and interested in running these codes to find the rice orthologue in Arabidopsis. I ran this code after downloading the input files and found the following error. Would you please help to sortout this issue.

(base) AwaisRiaz-01# python QTG_Finder_predict_orginal.py -gl AT_Seedsize_QTL_example.csv -sp "AT"
sklearn__version 1.5.2
Traceback (most recent call last):
File "/root/python/QTG_Finder_predict_orginal.py", line 72, in
df = pickle.load(pik_f) # Load the feature list with known causal genes used for training
^^^^^^^^^^^^^^^^^^
EOFError: Ran out of input
(base) AwaisRiaz-01#

Thank you

Awais Riaz

**Comment by linf545** [comment]
There maybe some misunderstanding of how the model works. For any target species that you are trying to make predictions on, you can use the pretrained model for target species. The model is already trained on corresponding orthologs in the target species.   If you are trying to make predictions on some rice QTL, you can 
python QTG_Finder_predict.py -gl your_rice_QTL_gene_LOC.csv -sp 'OS' 

'your_rice_QTL_gene_LOC.csv' is a file that you will need to provide. it is list of genes in the rice QTL that you are trying to prioritize. 

In you command you are trying to use  file 'AT_Seedsize_QTL_example.csv' as input, which does not exist. I only provided a Seteria QTL gene list as a example.

**Comment by Awais2426** [comment]
Thank you very much for you quick and contructed reply. 

I have tried the "python QTG_Finder_predict_orginal.py -gl SV_height_QTL_example.csv -sp 'SV'" code you mentioned and got the following error. would you please see and guide how can i sort out this.
(base) AwaisRiaz-01# python QTG_Finder_predict_orginal.py -gl SV_height_QTL_example.csv -sp 'SV'
sklearn__version 1.5.2
QTL: 2@91['height_59_DN13:dense'; 'height_67_DN13:dense'; 'height_67_DN14:dense'; 'height_67_DN14:sparse']
Traceback (most recent call last):
  File "/root/python/QTG_Finder_predict_orginal.py", line 82, in <module>
    Validation_set = pd.concat([Validation_set, df[df.ID == genes_in_QTL[i]]) # take out IDs that can not be found in the feature list
                                                   ^^^^^
AttributeError: 'RandomForestClassifier' object has no attribute 'ID'

Files in directory are as fellows
AT_model.dat
OS_model.dat
SV_model.dat
SB_model.dat
QTG_Finder_predict.py
QTG_Finder_Train.py
SV_height_QTL_example.csv

Thank you

**Comment by linf545** [comment]
Thank you for bringing up this issue. The model was trained with an earlier version of the libraries, so I've updated the environment requirements in the README file. You can now reinstall these libraries with the specified versions using conda or pip.
